In [3]:
import numpy as np

Bir veri tipi dir... 

In [4]:
np.array([1,5,2,3,6])

array([1, 5, 2, 3, 6])

In [5]:
arr = np.array([1,5,2,3,6])

In [6]:
type(arr)

numpy.ndarray

In [12]:
np.array([3.14, 5,6,2],dtype="int")

array([3, 5, 6, 2])

In [13]:
#Sıfırdan array oluşturma

In [15]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
#Belirli sayılardan oluşan bir array için 

In [57]:
# saedce 10 değerini içeren bir 3x3 matris
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
#Belirli aralıkta atlamalı sayı dizisi

In [22]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [24]:
#Belirli aralığı adet e bölecek şekilde dilimle

In [33]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#İstediğimiz bir ortalama değer ve std sapmaya sahip bir dizi de oluşturulabilir

In [34]:
a = np.arange(0,11,1)

In [35]:
a.std()

np.float64(3.1622776601683795)

In [36]:
a.mean()

np.float64(5.0)

In [38]:
#rastgele sayılardan oluşan 3x3 lük array
np.random.randint(0,10, (3,3))

array([[0, 2, 2],
       [2, 6, 9],
       [8, 4, 9]])

# **NUMPY** _ARRAY_ OZELLİKLERİ

##### ndim : Boyut Sayısı
##### shape: Boyut Bilgisi
##### size : Toplam Eleman Sayısı
##### dtype: Array veri tipi

In [46]:
np.random.randint(0, 6,10)
#Ya da 


array([5, 1, 5, 0, 4, 1, 5, 1, 3, 1])

In [48]:
a = np.random.randint(10, size=5)

In [53]:
#
print(a.ndim) #dimensions
print(a.shape) #kaça kaç
print(a.size) #Toplam eleman sayısı
print(a.dtype) #Sakladığı veri tipi

1
(5,)
5
int64


In [59]:
b = np.random.randint(10, size = (3,5))
# c = np.full((3,3),10) #Farkı ne?

In [62]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

2
(3, 5)
15
int64


# YENİDEN BOYUTLANDIRMA (ŞEKİLLENDİRME)

In [63]:
a = np.arange(0,9)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
b = a.reshape(3,3)

In [68]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
b.reshape(b.size)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# ARRAY BIRLESTIRME

In [77]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [78]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [79]:
np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
d = np.array([[1,2,3],
             [4,5,6]])

In [90]:
np.concatenate([d,d],axis=1) #0 satır, 1 sütun birleşirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# ARRAY AYIRMA (SPLIT)

##### YAPISI BİLİNEN ARRAYLER İÇİN

In [91]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [92]:
np.split(x, [3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [93]:
a,b,c = np.split(x, [3,5])

### İki boyutlu ayırma işlemi... 

In [94]:
m = np.arange(16).reshape(4,4)

In [95]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [97]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Array Sıralama

In [99]:
t = np.array([4,6,2,4,6,4,3,6,8,9,7,6])

In [100]:
np.sort(t)

array([2, 3, 4, 4, 4, 6, 6, 6, 6, 7, 8, 9])

### İki boyutlu array sıralama 

In [110]:
v1= np.random.randint(1, 100, (3,3))
v1

array([[98, 81, 19],
       [37, 52, 36],
       [28, 79, 74]])

In [111]:
v2 = np.linspace(0,1, 25).reshape(5,5)
v2

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

In [115]:
np.sort(v1, axis=1) # 0 Sütun, 1 satır

array([[19, 81, 98],
       [36, 37, 52],
       [28, 74, 79]])

# INDEX ILE ERISIM

In [117]:
m = np.random.randint(10, size=(3,5))
m

array([[5, 8, 4, 5, 0],
       [0, 6, 7, 6, 7],
       [1, 1, 1, 4, 2]])

In [120]:
m[0][2] = 100
m

array([[  5,   8, 100,   5,   0],
       [  0,   6,   7,   6,   7],
       [  1,   1,   1,   4,   2]])

In [121]:
m[0,2] = 150
m

array([[  5,   8, 150,   5,   0],
       [  0,   6,   7,   6,   7],
       [  1,   1,   1,   4,   2]])

#### sabit tipli array lere farklı tipte veri eklemek istersek

In [122]:
m

array([[  5,   8, 150,   5,   0],
       [  0,   6,   7,   6,   7],
       [  1,   1,   1,   4,   2]])

In [124]:
m[1,0] = 2.3
m
# Bu şeklilde kabul etmez çünkü işin içinde sabit bit tip var...

array([[  5,   8, 150,   5,   0],
       [  2,   6,   7,   6,   7],
       [  1,   1,   1,   4,   2]])

# SLICING

In [127]:
m[0:1:2]

array([[  5,   8, 150,   5,   0]])

In [132]:
d = np.random.randint(0,100, (4,4))
d

array([[31, 52, 14, 43],
       [44, 73, 34, 27],
       [87, 25, 13, 65],
       [21, 92, 32, 16]])

In [135]:
d[::2]

array([[31, 52, 14, 43],
       [87, 25, 13, 65]])

In [140]:
g = np.random.randint(1,100, size = 10)
g

array([ 3, 12, 18, 46, 71, 14,  1, 10, 63, 17])

In [141]:
g[::-1]

array([17, 63, 10,  1, 14, 71, 46, 18, 12,  3])

In [144]:
y = np.random.randint(0,100, size=(5,5))
y

array([[61, 34, 32, 63, 69],
       [19, 32,  9, 74, 68],
       [65,  5, 70, 31, 49],
       [41, 37, 43, 15, 41],
       [80, 42, 96, 56, 88]])

In [146]:
y[:,:2] #[satır, sütun]

array([[61, 34],
       [19, 32],
       [65,  5],
       [41, 37],
       [80, 42]])

In [148]:
y[0:1,::-1]

array([[69, 63, 32, 34, 61]])

In [151]:
y[1,::-1]

array([68, 74,  9, 32, 19])

In [152]:
y[0:2,::-1]

array([[69, 63, 32, 34, 61],
       [68, 74,  9, 32, 19]])

# ALT KUMELERDE ISLEM YAPARKEN

In [153]:
a = np.random.randint(100, size=(5,5))
a

array([[85, 53, 50, 51, 82],
       [64, 17, 26, 80,  5],
       [18, 66, 76, 67, 43],
       [33, 73,  4,  9, 75],
       [90,  3, 43,  7, 54]])

In [155]:
b = a[0:3,1:4]
b

array([[53, 50, 51],
       [17, 26, 80],
       [66, 76, 67]])

In [156]:
b[0,0] = 9999
b [1,1] = 8888

In [157]:
b

array([[9999,   50,   51],
       [  17, 8888,   80],
       [  66,   76,   67]])

In [158]:
a

array([[  85, 9999,   50,   51,   82],
       [  64,   17, 8888,   80,    5],
       [  18,   66,   76,   67,   43],
       [  33,   73,    4,    9,   75],
       [  90,    3,   43,    7,   54]])

In [160]:
a = np.random.randint(100, size=(5,5))
a

array([[19, 40, 96, 35, 92],
       [31, 17, 28, 49, 99],
       [87, 83, 44, 37, 11],
       [97, 73, 69, 35, 44],
       [52, 74, 55, 51, 30]])

In [161]:
b = a[0:3,1:4].copy()
b

array([[40, 96, 35],
       [17, 28, 49],
       [83, 44, 37]])

In [162]:
b[0,0] = 77777

In [163]:
a

array([[19, 40, 96, 35, 92],
       [31, 17, 28, 49, 99],
       [87, 83, 44, 37, 11],
       [97, 73, 69, 35, 44],
       [52, 74, 55, 51, 30]])

In [164]:
b

array([[77777,    96,    35],
       [   17,    28,    49],
       [   83,    44,    37]])

# HAVALI INDEX (FANCY) 

##### Olayı, listenin içinden listedeki elemanları getirmek... :)

In [169]:
a = np.random.randint(101, size=70)
a

array([ 90,  37,  69,  51,  34,  50,  70,  90,  11,  24,  65,  90,  90,
        26,  55,  22,  91,  76,  43,  59,   9,   6,  74,  25,  69,  85,
        21,  65,  51,  58,  20,  41,  39,  77,  34,  28,  84,  13,  22,
         7,   7,  97,  53, 100,   7,   1,   6,  82,  54,  27,  21,  95,
         8,  96,  87,   2,  30,   8,  22,  78,  50,  59,   4,  73,   8,
        61,  61,  12,  49,  76])

In [171]:
idxs = [5,6,8,9,12,25,36,48]
a[idxs]

array([50, 70, 11, 24, 90, 85, 84, 54])

### IKI BOYUTTA FANCY INDEX

In [174]:
f = np.random.randint(255, size=(640,400))
f

array([[  7, 159, 186, ...,  41, 140, 150],
       [132,  87, 216, ..., 223,  78, 132],
       [ 41, 180, 102, ..., 232, 142, 140],
       ...,
       [  9, 136,  72, ..., 196,  75, 176],
       [  1, 102,  18, ...,  30,  75,  44],
       [ 39, 133, 106, ..., 124, 135, 122]])

In [175]:
satir = [5,6,9]
sutun = [6,75,8]
f[satir, sutun]

array([249,   7,  97])

# KOSULLU ELEMAN İŞLEMLERİ

In [178]:
s = np.random.randint(5, size=5)
s

array([0, 2, 0, 3, 0])

In [179]:
s > 2

array([False, False, False,  True, False])

In [180]:
s [s > 2]

array([3])

# MATEMATİKSEL İŞLEMLER 

### Ikı yolu var
##### Mat operatorler
##### ufunc işlemleri

In [181]:
v = np.random.randint(0,100, size=5)
v

array([34,  5, 97, 55, 70])

In [182]:
v - 1

array([33,  4, 96, 54, 69])

In [183]:
v /5

array([ 6.8,  1. , 19.4, 11. , 14. ])

In [184]:
# ufunc 
np.subtract(v, 3)

array([31,  2, 94, 52, 67])

In [186]:
# np.add, np.multiply, np.divide, np.power, np.mod, np.absolute

In [187]:
# np.cos, np.sin, np.logX

In [190]:
# cheat sheet -> Kopya Kağıdı
# Numpy Mathematics cheat Sheet

# Istatistiksel Hesaplamalar

In [191]:
v.std()

np.float64(31.2755495555234)

In [192]:
v.mean()

np.float64(52.2)

In [193]:
v.var()

np.float64(978.1600000000001)

In [194]:
v.sum()

np.int64(261)

In [195]:
v.min()

np.int64(5)

In [196]:
v.max()

np.int64(97)

# NUMPY ILE IKI BILINMEYENLI DENKLER COZUMU

##### x+y = 11
##### 2x+5y = 34

In [198]:
a = np.array([[1,1],[2,5]])
b = np.array([11,34])

In [199]:
sonuc = np.linalg.solve(a,b)

In [200]:
sonuc

array([7., 4.])